### PR TITLE
Fix `ssa_greedy_optimize` if output hyperindices

### LINKED ISSUE #23: `ssa_greedy_optimize` crashes for non-empty `output`
When `!isempty(output)`, `target_inds_histogram` dictionary does not contain keys from `output` indices due to line https://github.com/bsc-quantic/OptimizedEinsum.jl/blob/9d52b4a77416db0af9ba882eef5de5b3535e16c4/src/Solvers/Greedy.jl#L75-L79

This makes the following code to crash. https://github.com/bsc-quantic/OptimizedEinsum.jl/blob/9d52b4a77416db0af9ba882eef5de5b3535e16c4/src/Solvers/Greedy.jl#L112-L118

If we can be sure that output indices are gonna be open indices (not open hyperindices), then it could be easily solved by filtering output indices in `[a..., b...]` and `c`.

### PR DESCRIPTION
**Pull request by jofrevalles**
Fix #23.

### Summary
Now it is possible to find the path for non-empty `output` using the `Greedy` and `RandomGreedy` solvers. We also added an exception that raises an error whenever a path does contain hyperindices at the `ouput`. 

### Example
Now the test in [test/ContractionPath_test.jl](https://github.com/bsc-quantic/OptimizedEinsum.jl/blob/master/test/ContractionPath_test.jl) works properly:
```julia
Test Summary:   | Pass  Total  Time
ContractionPath |   10     10  0.9s
Test.DefaultTestSet("ContractionPath", Any[], 10, false, false, true, 1.675080747261861e9, 1.675080748144805e9)
```

### CODE REVIEW

File: src/Solvers/Greedy.jl [hunk 1]
```diff
@@ -109,11 +114,11 @@ function ssa_greedy_optimize(inputs, output, size, choose_fn=greedy_choose_simpl
         push!(ssa_path, (ssa_id_i, ssa_id_j))
 
         # update ocurrence histogram
-        for ind ∈ [a..., b...]
+        for ind ∈ filter(x -> x ∈ keys(target_inds_histogram), [a...,b...])
```
Comment (mofeing) [inline src/Solvers/Greedy.jl:117]:
```suggestion
        for ind ∈ Iterators.filter(x -> x ∈ keys(target_inds_histogram), [a...,b...])
```

File: src/Solvers/Greedy.jl [hunk 2]
```diff
@@ -109,11 +114,11 @@ function ssa_greedy_optimize(inputs, output, size, choose_fn=greedy_choose_simpl
...
             target_inds_histogram[ind] -= 1
         end
 
-        for ind ∈ c
+        for ind ∈ filter(x -> x ∈ keys(target_inds_histogram), c)
```
Comment (mofeing) [inline src/Solvers/Greedy.jl:121]:
```suggestion
        for ind ∈ Iterators.filter(x -> x ∈ keys(target_inds_histogram), c)
```

**Review by mofeing — CHANGES_REQUESTED** [review]
Great! Maybe could you use `Iterators.filter` instead?
